### ISSUE TITLE
std::invalid_argument with examples after building with gbs  

### ISSUE THREAD

**Issue by nscotto** [nnstreamer/nntrainer#893]
Hello, I've just built nntrainer with gbs and after installing it on the device when running the examples I get a C++ exceptions.
```
/lib/nntrainer/bin/applications# ./nntrainer_mnist
terminate called after throwing an instance of 'std::invalid_argument'
  what():  cannot register factory with already taken key:
 ```
This seems to happen before the main even started, as you can see I am not passing the right number of argument so the example should just quit.
Here is the backtrace from gdb:
```
#0  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x42b6bc20 in __GI_abort () at abort.c:79
#2  0x42d89100 in __gnu_cxx::__verbose_terminate_handler() () from /lib/libstdc++.so.6
#3  0x42d87a64 in ?? () from /lib/libstdc++.so.6
#4  0x42d87ab2 in std::terminate() () from /lib/libstdc++.so.6
#5  0x42d87cd2 in __cxa_throw () from /lib/libstdc++.so.6
#6  0xb605a0ae in nntrainer::AppContext::registerFactory<ml::train::Optimizer>(std::function<std::unique_ptr<ml::train::Optimizer, std::default_delete<ml::train::Optimizer> > (std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (this=this@entry=0xb61d293c <nntrainer::AppContext::Global()::instance>, factory=..., key=...,
    int_key=<optimized out>, int_key@entry=0) at /usr/lib/gcc/armv7l-tizen-linux-gnueabi/9.2.0/include/c++/bits/allocator.h:153
#7  0xb605a382 in nntrainer::AppContext::registerFactory<ml::train::Optimizer> (this=0xb61d293c <nntrainer::AppContext::Global()::instance>, factory=<optimized out>, key=..., int_key=0)
    at /usr/lib/gcc/armv7l-tizen-linux-gnueabi/9.2.0/include/c++/new:174
#8  0xb6058cd2 in global constructors keyed to 65535_0_databuffer.cpp.o.91324 () at /usr/lib/gcc/armv7l-tizen-linux-gnueabi/9.2.0/include/c++/bits/hashtable_policy.h:433
#9  0x41010268 in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0xbe1ff794, env=env@entry=0xbe1ff79c) at dl-init.c:72
#10 0x4101036c in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:30
#11 _dl_init (main_map=0x41031910, argc=1, argv=0xbe1ff794, env=0xbe1ff79c) at dl-init.c:136
#12 0x41000a84 in ?? () from /lib/ld-linux.so.3
```
Any help would be appreciated.
Thank you,

**Comment by zhoonit** [comment]
Thank you for posting the issue, as key is empty in your log, there must be a static initialization order problem. 
I uploaded a patch that may solve the issue. Could you checkout #894 and see if problem is solved?

**Comment by nscotto** [comment]
Thank you for the quick support!
That solves the issue. :)

Before closing it, I am getting an error during training when running mnist_test:
```
/lib/nntrainer/bin/applications# ./nntrainer_mnist test_models/models/mnist.ini
Error during train          ]  ( Training Loss: 0 )
```
do you have an idea about what could be the problem?

Thank you.

**Comment by zhoonit** [comment]
Could you check the log and share?

our tag is `nntrainer`

You can either check with `dlogutil` or using `tizen studio`
Please refer to https://developer.tizen.org/dev-guide/2.3.1/org.tizen.guides/html/native/system/dlog_n.htm#dlogutil

**Comment by nscotto** [comment]
Here is the log when using the previous command:
```
~# dlogutil nntrainer:*
Buffer main is set
argc = 2, optind = 1, Kb 16, rotate 4
--------- beginning of /dev/log_main
I/nntrainer(26760): ==========================parsing ini...
I/nntrainer(26760): not-allowed property for the layer throws error
I/nntrainer(26760): valid property with invalid value throws error as well
I/nntrainer(26760): [MMapedMemory] fd creation is not supported in this platform
I/nntrainer(26760): [MMapedMemory] fd creation is not supported in this platform
```

**Comment by zhoonit** [comment]
https://github.com/nnstreamer/nntrainer/pull/912
should fix the issue.

Could you check this out?

**Comment by nscotto** [comment]
It didn't fix the issue.
Maybe I am missing something about the usage, the documentation isn't 100% clear to me, mainly the part about `Tensorflow/Training_Keras.py`, `dataset.py` and `mnist_trainingSet.dat`.
If I do a `find` on my system, I can't find any `dataset.py` nor `Training_Keras.py`

**Comment by zhoonit** [comment]
> It didn't fix the issue.
> Maybe I am missing something about the usage, the documentation isn't 100% clear to me, mainly the part about `Tensorflow/Training_Keras.py`, `dataset.py` and `mnist_trainingSet.dat`.
> If I do a `find` on my system, I can't find any `dataset.py` nor `Training_Keras.py`

I've spotted two problem regarding the issue.

1. about the application 🐳 
`dataset.py` and `Training_Keras.py` is not necessary to run the program. You need to have the `mnist_trainingSet.dat`.

It's `nntrainer_mnist` has [hard coded path](https://github.com/nnstreamer/nntrainer/blob/main/Applications/MNIST/jni/main.cpp#L154) of `mnist_trainingSet.dat`. So it has to be run at the folder of `${libdir}/nntrainer/bin/applications` and require `mnist_trainingSet.dat` at the same folder. 
Could you confirm if `${libdir}/nntrainer/bin/applications` contains `mnist_trinaingSet.dat`?

#912 commit-1 fixes this issue

2. Memory management 🌴 
#889 fixes this issue

3. Save Path 🥯 
save path was pointing to non existing path.

#912 commit-2 fixes this issue

if 🌴, 🥯  meets but 🐳  is not, could you clean and try as below?
`gbs build --include-all --arch=${arch} --clean-repos --clean` 

I apologize for the untidy example and documentations. 
If you would like to contribute to tidy things up, we are more than welcome :)

**Comment by nscotto** [comment]
It's working after #912 (merged locally with #894 - needs to be merged to master), thank you!
